import PDFDocument from 'pdfkit';

interface TransactionPdfOptions {
  title: string;
  filterSummary: string;
  generatedBy: string;
  generatedAt: string;
  entries: any[];
}

interface ExecutiveSummaryPdfOptions {
  year: number;
  month: number;
  generatedBy: string;
  generatedAt: string;
  reportData: any;
}

interface ArchivePdfOptions {
  yearMonth: string;
  generatedBy: string;
  generatedAt: string;
  archive: any;
  reopenLogs?: any[];
}

function formatMoney(val: number | string): string {
  const num = Number(val || 0);
  return `PHP ${num.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export function generateTransactionsPdfBuffer(options: TransactionPdfOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: 30, bufferPages: true });
      const buffers: Buffer[] = [];
      doc.on('data', chunk => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      // Header Banner
      doc.rect(30, 25, 782, 55).fill('#1E293B');
      
      doc.fillColor('#FFFFFF').fontSize(14).font('Helvetica-Bold').text('CONTACTPOINT 360 - ASSET INVENTORY SYSTEM', 45, 35);
      doc.fillColor('#94A3B8').fontSize(10).font('Helvetica').text('TRANSACTION TRACKER AUDIT LOG & EXPENSE DETAIL REPORT', 45, 53);

      // Metadata card
      doc.rect(30, 90, 782, 45).fill('#F8FAFC').stroke('#E2E8F0');
      doc.fillColor('#334155').fontSize(9).font('Helvetica-Bold').text('Filter Scope:', 40, 98);
      doc.fillColor('#64748B').font('Helvetica').text(options.filterSummary, 110, 98, { width: 400 });

      doc.fillColor('#334155').fontSize(9).font('Helvetica-Bold').text('Generated By:', 530, 98);
      doc.fillColor('#64748B').font('Helvetica').text(`${options.generatedBy} on ${options.generatedAt}`, 600, 98, { width: 200 });

      doc.fillColor('#334155').fontSize(9).font('Helvetica-Bold').text('Total Records:', 40, 118);
      doc.fillColor('#059669').font('Helvetica-Bold').text(`${options.entries.length} Transactions`, 110, 118);

      const grandTotal = options.entries.reduce((acc, item) => acc + Number(item.total || 0), 0);
      doc.fillColor('#334155').fontSize(9).font('Helvetica-Bold').text('Grand Total:', 530, 118);
      doc.fillColor('#2563EB').font('Helvetica-Bold').text(formatMoney(grandTotal), 600, 118);

      // Table Header
      let y = 145;
      const colX = [35, 100, 230, 340, 420, 520, 570, 640, 710, 770];
      const colW = [60, 125, 105, 75, 95, 45, 65, 65, 55, 35];

      doc.rect(30, y, 782, 22).fill('#475569');
      doc.fillColor('#FFFFFF').fontSize(8).font('Helvetica-Bold');
      doc.text('DATE', colX[0], y + 6);
      doc.text('DESCRIPTION', colX[1], y + 6);
      doc.text('CATEGORY', colX[2], y + 6);
      doc.text('LOCATION', colX[3], y + 6);
      doc.text('SUPPLIER', colX[4], y + 6);
      doc.text('QTY', colX[5], y + 6, { width: colW[5], align: 'right' });
      doc.text('UNIT PRICE', colX[6], y + 6, { width: colW[6], align: 'right' });
      doc.text('TOTAL', colX[7], y + 6, { width: colW[7], align: 'right' });
      doc.text('STATUS', colX[8], y + 6);
      doc.text('FILES', colX[9], y + 6, { width: colW[9], align: 'center' });

      y += 22;

      // Table Rows
      options.entries.forEach((item, index) => {
        if (y > 520) {
          doc.addPage();
          y = 35;
          // Re-draw header on new page
          doc.rect(30, y, 782, 22).fill('#475569');
          doc.fillColor('#FFFFFF').fontSize(8).font('Helvetica-Bold');
          doc.text('DATE', colX[0], y + 6);
          doc.text('DESCRIPTION', colX[1], y + 6);
          doc.text('CATEGORY', colX[2], y + 6);
          doc.text('LOCATION', colX[3], y + 6);
          doc.text('SUPPLIER', colX[4], y + 6);
          doc.text('QTY', colX[5], y + 6, { width: colW[5], align: 'right' });
          doc.text('UNIT PRICE', colX[6], y + 6, { width: colW[6], align: 'right' });
          doc.text('TOTAL', colX[7], y + 6, { width: colW[7], align: 'right' });
          doc.text('STATUS', colX[8], y + 6);
          doc.text('FILES', colX[9], y + 6, { width: colW[9], align: 'center' });
          y += 22;
        }

        const bgColor = index % 2 === 0 ? '#FFFFFF' : '#F1F5F9';
        doc.rect(30, y, 782, 20).fill(bgColor);
        doc.fillColor('#1E293B').fontSize(7.5).font('Helvetica');

        const dtStr = item.transactionDate ? new Date(item.transactionDate).toLocaleDateString() : '';
        const descStr = (item.itemDescription || '').substring(0, 26);
        const catStr = (item.category || '').substring(0, 18);
        const locStr = (item.destinationName || item.site?.name || 'N/A').substring(0, 14);
        const supStr = (item.supplierName || item.supplier?.name || 'Unassigned').substring(0, 18);
        const qtyStr = `${Number(item.qty || 0)} ${item.unit || 'PC'}`;
        const priceStr = formatMoney(item.unitPrice);
        const totalStr = formatMoney(item.total);
        const statusStr = item.status || 'PENDING';
        const fileCount = Array.isArray(item.attachments) ? item.attachments.length : (item.sourceDocumentUrl ? 1 : 0);

        doc.text(dtStr, colX[0], y + 5);
        doc.text(descStr, colX[1], y + 5);
        doc.text(catStr, colX[2], y + 5);
        doc.text(locStr, colX[3], y + 5);
        doc.text(supStr, colX[4], y + 5);
        doc.text(qtyStr, colX[5], y + 5, { width: colW[5], align: 'right' });
        doc.text(priceStr, colX[6], y + 5, { width: colW[6], align: 'right' });
        doc.font('Helvetica-Bold').text(totalStr, colX[7], y + 5, { width: colW[7], align: 'right' });
        doc.font('Helvetica').text(statusStr, colX[8], y + 5);
        doc.text(String(fileCount), colX[9], y + 5, { width: colW[9], align: 'center' });

        y += 20;
      });

      // Page Footers
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        doc.rect(30, 560, 782, 0.5).fill('#CBD5E1');
        doc.fillColor('#94A3B8').fontSize(7.5).font('Helvetica');
        doc.text('ContactPoint 360 — Internal Operations & Financial Control System', 30, 568);
        doc.text(`Page ${i + 1} of ${range.count}`, 750, 568, { align: 'right' });
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

export function generateExecutiveSummaryPdfBuffer(options: ExecutiveSummaryPdfOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', layout: 'portrait', margin: 35, bufferPages: true });
      const buffers: Buffer[] = [];
      doc.on('data', chunk => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      const r = options.reportData || {};
      const totalOpex = Number(r.totalOpex || 0);
      const totalCapex = Number(r.totalCapex || 0);
      const grandTotal = totalOpex + totalCapex;
      const momDelta = Number(r.momDeltaPercentage || 0);

      // Header Banner
      doc.rect(35, 30, 525, 60).fill('#0F172A');
      doc.fillColor('#FFFFFF').fontSize(16).font('Helvetica-Bold').text('CONTACTPOINT 360', 50, 42);
      doc.fillColor('#94A3B8').fontSize(11).font('Helvetica').text(`EXECUTIVE FINANCIAL ROLLUP REPORT — ${options.year}-${String(options.month).padStart(2, '0')}`, 50, 62);

      // Metadata bar
      doc.rect(35, 100, 525, 30).fill('#F1F5F9');
      doc.fillColor('#475569').fontSize(8.5).font('Helvetica').text(`Generated By: ${options.generatedBy} | Date: ${options.generatedAt}`, 45, 110);

      // KPI Metric Cards (3 cards)
      const cardY = 140;
      doc.rect(35, cardY, 165, 65).fill('#EFF6FF').stroke('#BFDBFE');
      doc.fillColor('#1E40AF').fontSize(8).font('Helvetica-Bold').text('TOTAL EXPENDITURE', 45, cardY + 10);
      doc.fillColor('#1E3A8A').fontSize(12).font('Helvetica-Bold').text(formatMoney(grandTotal), 45, cardY + 30);

      doc.rect(215, cardY, 165, 65).fill('#ECFDF5').stroke('#A7F3D0');
      doc.fillColor('#065F46').fontSize(8).font('Helvetica-Bold').text('OPEX SPEND', 225, cardY + 10);
      doc.fillColor('#064E3B').fontSize(12).font('Helvetica-Bold').text(formatMoney(totalOpex), 225, cardY + 30);

      doc.rect(395, cardY, 165, 65).fill('#F5F3FF').stroke('#DDD6FE');
      doc.fillColor('#5B21B6').fontSize(8).font('Helvetica-Bold').text('CAPEX SPEND', 405, cardY + 10);
      doc.fillColor('#4C1D95').fontSize(12).font('Helvetica-Bold').text(formatMoney(totalCapex), 405, cardY + 30);

      // Month-over-Month Delta Box
      let y = 220;
      doc.rect(35, y, 525, 35).fill(momDelta >= 0 ? '#FEF2F2' : '#F0FDF4').stroke(momDelta >= 0 ? '#FCA5A5' : '#86EFAC');
      doc.fillColor(momDelta >= 0 ? '#991B1B' : '#166534').fontSize(9.5).font('Helvetica-Bold');
      doc.text(`Month-over-Month Variance: ${momDelta >= 0 ? '+' : ''}${momDelta.toFixed(1)}% vs. Prior Month`, 45, y + 10);

      y += 50;

      // Spend by Destination Table
      doc.fillColor('#0F172A').fontSize(11).font('Helvetica-Bold').text('1. Spend Breakdown by Destination / Site', 35, y);
      y += 18;
      doc.rect(35, y, 525, 18).fill('#334155');
      doc.fillColor('#FFFFFF').fontSize(8).font('Helvetica-Bold').text('LOCATION / SITE NAME', 45, y + 4);
      doc.text('TOTAL SPEND (PHP)', 400, y + 4, { width: 150, align: 'right' });
      y += 18;

      const bySite = Array.isArray(r.byDestination) ? r.byDestination : [];
      if (bySite.length === 0) {
        doc.fillColor('#64748B').fontSize(8.5).font('Helvetica-Oblique').text('No destination records found.', 45, y + 4);
        y += 20;
      } else {
        bySite.forEach((site: any, idx: number) => {
          doc.rect(35, y, 525, 16).fill(idx % 2 === 0 ? '#FFFFFF' : '#F8FAFC');
          doc.fillColor('#1E293B').fontSize(8).font('Helvetica').text(site.destinationName || site.name || 'Unassigned', 45, y + 4);
          doc.text(formatMoney(site.total || site.amount || 0), 400, y + 4, { width: 150, align: 'right' });
          y += 16;
        });
      }

      y += 15;

      // Spend by Category Table
      doc.fillColor('#0F172A').fontSize(11).font('Helvetica-Bold').text('2. Spend Breakdown by Category', 35, y);
      y += 18;
      doc.rect(35, y, 525, 18).fill('#334155');
      doc.fillColor('#FFFFFF').fontSize(8).font('Helvetica-Bold').text('CATEGORY NAME', 45, y + 4);
      doc.text('TOTAL SPEND (PHP)', 400, y + 4, { width: 150, align: 'right' });
      y += 18;

      const byCat = Array.isArray(r.byCategory) ? r.byCategory : [];
      if (byCat.length === 0) {
        doc.fillColor('#64748B').fontSize(8.5).font('Helvetica-Oblique').text('No category records found.', 45, y + 4);
        y += 20;
      } else {
        byCat.forEach((cat: any, idx: number) => {
          doc.rect(35, y, 525, 16).fill(idx % 2 === 0 ? '#FFFFFF' : '#F8FAFC');
          doc.fillColor('#1E293B').fontSize(8).font('Helvetica').text((cat.category || cat.name || 'UNassigned').replace(/_/g, ' '), 45, y + 4);
          doc.text(formatMoney(cat.total || cat.amount || 0), 400, y + 4, { width: 150, align: 'right' });
          y += 16;
        });
      }

      // Footers
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        doc.rect(35, 780, 525, 0.5).fill('#CBD5E1');
        doc.fillColor('#94A3B8').fontSize(8).font('Helvetica');
        doc.text('ContactPoint 360 — Confidential Executive Financial Summary', 35, 788);
        doc.text(`Page ${i + 1} of ${range.count}`, 500, 788, { align: 'right' });
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

export function generateArchivePdfBuffer(options: ArchivePdfOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', layout: 'portrait', margin: 35, bufferPages: true });
      const buffers: Buffer[] = [];
      doc.on('data', chunk => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      const arch = options.archive || {};
      const snapshot = typeof arch.summarySnapshot === 'string' ? JSON.parse(arch.summarySnapshot) : (arch.summarySnapshot || {});
      const lockedUser = arch.lockedByUser?.name || arch.lockedByUser?.email || 'Super Admin';
      const lockedDate = arch.lockedAt ? new Date(arch.lockedAt).toLocaleString() : 'N/A';

      // Header Banner
      doc.rect(35, 30, 525, 60).fill('#0F172A');
      doc.fillColor('#FFFFFF').fontSize(15).font('Helvetica-Bold').text('HISTORICAL LOCKED FINANCIAL ARCHIVE', 50, 42);
      doc.fillColor('#38BDF8').fontSize(11).font('Helvetica').text(`OFFICIAL IMMUTABLE SNAPSHOT — PERIOD: ${options.yearMonth}`, 50, 62);

      // Lock Security Badge
      doc.rect(35, 100, 525, 45).fill('#F0FDF4').stroke('#86EFAC');
      doc.fillColor('#166534').fontSize(9).font('Helvetica-Bold').text('🔒 IMMUTABLE LOCK METADATA:', 45, 108);
      doc.fillColor('#15803D').fontSize(8.5).font('Helvetica').text(`Locked By: ${lockedUser} | Locked Timestamp: ${lockedDate}`, 45, 124);

      // Re-open Audit Notice if present
      let y = 155;
      if (Array.isArray(options.reopenLogs) && options.reopenLogs.length > 0) {
        options.reopenLogs.forEach((log) => {
          doc.rect(35, y, 525, 32).fill('#FFFBEB').stroke('#FCD34D');
          doc.fillColor('#92400E').fontSize(8.5).font('Helvetica-Bold').text(`⚠️ PERIOD OVERRIDE AUDIT LOG:`, 45, y + 6);
          doc.fillColor('#B45309').fontSize(8).font('Helvetica').text(`Unlocked on ${new Date(log.createdAt).toLocaleString()} by ${log.user?.name || log.user?.email || 'Super Admin'} | Action: ${log.action}`, 45, y + 18);
          y += 38;
        });
      }

      // Summary Totals
      const totalOpex = Number(snapshot.totalOpex || snapshot.opexTotal || 0);
      const totalCapex = Number(snapshot.totalCapex || snapshot.capexTotal || 0);
      const grandTotal = totalOpex + totalCapex;

      doc.rect(35, y, 525, 60).fill('#F8FAFC').stroke('#E2E8F0');
      doc.fillColor('#334155').fontSize(9).font('Helvetica-Bold').text('LOCKED ARCHIVE SUMMARY SNAPSHOT', 45, y + 10);
      doc.fillColor('#0F172A').fontSize(11).font('Helvetica-Bold').text(`Total Spend: ${formatMoney(grandTotal)}`, 45, y + 32);
      doc.fillColor('#059669').fontSize(9.5).font('Helvetica').text(`(OPEX: ${formatMoney(totalOpex)} | CAPEX: ${formatMoney(totalCapex)})`, 280, y + 34);

      y += 75;

      // Spend by Destination
      doc.fillColor('#0F172A').fontSize(10.5).font('Helvetica-Bold').text('1. Locked Spend by Destination / Site', 35, y);
      y += 16;
      doc.rect(35, y, 525, 18).fill('#475569');
      doc.fillColor('#FFFFFF').fontSize(8).font('Helvetica-Bold').text('SITE / LOCATION', 45, y + 4);
      doc.text('AMOUNT (PHP)', 400, y + 4, { width: 150, align: 'right' });
      y += 18;

      const bySite = Array.isArray(snapshot.byDestination) ? snapshot.byDestination : [];
      if (bySite.length === 0) {
        doc.fillColor('#64748B').fontSize(8).font('Helvetica-Oblique').text('No destination breakdown recorded.', 45, y + 4);
        y += 18;
      } else {
        bySite.forEach((item: any, idx: number) => {
          doc.rect(35, y, 525, 16).fill(idx % 2 === 0 ? '#FFFFFF' : '#F1F5F9');
          doc.fillColor('#1E293B').fontSize(8).font('Helvetica').text(item.destinationName || item.name || 'Unassigned', 45, y + 4);
          doc.text(formatMoney(item.total || item.amount || 0), 400, y + 4, { width: 150, align: 'right' });
          y += 16;
        });
      }

      y += 15;

      // Spend by Category
      doc.fillColor('#0F172A').fontSize(10.5).font('Helvetica-Bold').text('2. Locked Spend by Category', 35, y);
      y += 16;
      doc.rect(35, y, 525, 18).fill('#475569');
      doc.fillColor('#FFFFFF').fontSize(8).font('Helvetica-Bold').text('CATEGORY', 45, y + 4);
      doc.text('AMOUNT (PHP)', 400, y + 4, { width: 150, align: 'right' });
      y += 18;

      const byCat = Array.isArray(snapshot.byCategory) ? snapshot.byCategory : [];
      if (byCat.length === 0) {
        doc.fillColor('#64748B').fontSize(8).font('Helvetica-Oblique').text('No category breakdown recorded.', 45, y + 4);
        y += 18;
      } else {
        byCat.forEach((item: any, idx: number) => {
          doc.rect(35, y, 525, 16).fill(idx % 2 === 0 ? '#FFFFFF' : '#F1F5F9');
          doc.fillColor('#1E293B').fontSize(8).font('Helvetica').text((item.category || item.name || 'Unassigned').replace(/_/g, ' '), 45, y + 4);
          doc.text(formatMoney(item.total || item.amount || 0), 400, y + 4, { width: 150, align: 'right' });
          y += 16;
        });
      }

      // Footers
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        doc.rect(35, 780, 525, 0.5).fill('#CBD5E1');
        doc.fillColor('#94A3B8').fontSize(8).font('Helvetica');
        doc.text('ContactPoint 360 — Official Historical Financial Archive', 35, 788);
        doc.text(`Page ${i + 1} of ${range.count}`, 500, 788, { align: 'right' });
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}
